name: deploy_frontend
#deploys when push is made from frontend folder
on:
  push:
    branches: [main]
    paths:
      - "frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIAL}}

      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch --account-name azureresumetej --auth-mode key -d '$web' -s frontend/
      - name: Purge CDN endpoint
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az cdn endpoint purge --content-paths  "/*" --profile-name "myCdnProfile" --name "myEndPointTej" --resource-group "portfoli0"

      # Azure logout
      - name: logout
        run: |
          az logout
        if: always()
